language: python

python:
    - 3.8

install:
  - pip install -r requirements/dev.txt

script:
  - cd department-app
  - python -m unittest tests.test_crud
  - python -m unittest tests.test_api
  - coverage erase
  - coverage run -m unittest && coverage html
  - cd ..
  - pylint --output-format=text department-app

after_success:
  - codecov
